CREATE TABLE IF NOT EXISTS pessoas (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) NULL UNIQUE,
    data_nascimento DATE NULL,
    telefone VARCHAR(20) NULL,
    email VARCHAR(150) NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id INT4 NOT NULL UNIQUE,
    login VARCHAR(80) NOT NULL UNIQUE,
    email_login VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    nivel_acesso VARCHAR(20) NOT NULL DEFAULT 'usuario' CHECK (nivel_acesso IN ('usuario', 'administrador', 'gerente')),
    ultimo_login_em TIMESTAMP NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuarios_pessoas FOREIGN KEY (pessoa_id) REFERENCES pessoas(id)
);

CREATE TABLE IF NOT EXISTS receitas (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    valor NUMERIC(14, 2) NOT NULL,
    data_recebimento DATE NOT NULL,
    categoria VARCHAR(80) NULL,
    observacoes TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'prevista' CHECK (status IN ('prevista', 'recebida')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receitas_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS despesas (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    valor NUMERIC(14, 2) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE NULL,
    categoria VARCHAR(80) NULL,
    observacoes TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'paga')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_despesas_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS contas_fixas (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    valor_previsto NUMERIC(14, 2) NOT NULL,
    dia_vencimento INT4 NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 31),
    categoria VARCHAR(80) NULL,
    periodicidade VARCHAR(20) NOT NULL DEFAULT 'mensal' CHECK (periodicidade IN ('mensal', 'bimestral', 'trimestral', 'anual')),
    proximo_vencimento DATE NULL,
    observacoes TEXT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contas_fixas_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS cartoes (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    nome VARCHAR(120) NOT NULL,
    bandeira VARCHAR(50) NULL,
    apelido VARCHAR(80) NULL,
    ultimos_digitos VARCHAR(4) NOT NULL,
    limite NUMERIC(14, 2) NULL,
    dia_fechamento INT4 NOT NULL CHECK (dia_fechamento BETWEEN 1 AND 31),
    dia_vencimento INT4 NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 31),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cartoes_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS faturas_cartao (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    cartao_id INT4 NOT NULL,
    competencia VARCHAR(7) NOT NULL,
    data_fechamento DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    valor_total NUMERIC(14, 2) NOT NULL,
    valor_pago NUMERIC(14, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'aberta' CHECK (status IN ('aberta', 'fechada', 'paga')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_faturas_cartao_competencia UNIQUE (cartao_id, competencia),
    CONSTRAINT fk_faturas_cartao_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_faturas_cartao_cartoes FOREIGN KEY (cartao_id) REFERENCES cartoes(id)
);

CREATE TABLE IF NOT EXISTS compras_cartao (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    cartao_id INT4 NOT NULL,
    fatura_id INT4 NULL,
    descricao VARCHAR(150) NOT NULL,
    valor NUMERIC(14, 2) NOT NULL,
    data_compra DATE NOT NULL,
    categoria VARCHAR(80) NULL,
    observacoes TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'lancada' CHECK (status IN ('lancada', 'cancelada')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_compras_cartao_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_compras_cartao_cartoes FOREIGN KEY (cartao_id) REFERENCES cartoes(id),
    CONSTRAINT fk_compras_cartao_faturas FOREIGN KEY (fatura_id) REFERENCES faturas_cartao(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS pix_transacoes (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('enviado', 'recebido')),
    valor NUMERIC(14, 2) NOT NULL,
    data_pix DATE NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    conta VARCHAR(120) NULL,
    categoria VARCHAR(80) NULL,
    observacoes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pix_transacoes_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS recebiveis (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT4 NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    valor_previsto NUMERIC(14, 2) NOT NULL,
    data_esperada DATE NOT NULL,
    data_recebimento DATE NULL,
    origem VARCHAR(120) NULL,
    categoria VARCHAR(80) NULL,
    observacoes TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'recebido', 'atrasado')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recebiveis_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);


ALTER TABLE pessoas ALTER COLUMN cpf DROP NOT NULL;
